### ISSUE TITLE
redirect to new.reddit option

### ISSUE THREAD

**Issue by MesaBlack** [tom-james-watson/old-reddit-redirect#109]

**Comment by pabuisson** [comment]
Hey :wave: I actually find this request interesting now that reddit offer a "new new" version.

The "old new" version was working OK for me, and I found addons doing just that. But your addon is the oldest one with a much larger user base, and I was thinking having one single addon to handle reddit redirections to either old.reddit.com or to new.reddit.com (the "old new" version) would be great and a more solid/reliable solution for the community. 

I see this issue was marked as "completed" but don't find any settings in the addon or any commit that seems related, so I guess it was rather a "won't fix" resolution? 

Anyway, I'd love to hear your thoughts on this, and if this is something you don't consider by lack of time or rather because you think it does not have its place in your addon.

**Comment by tom-james-watson** [comment]
Hello! Yeah it just marked as "completed" unless you select "won't fix" from the dropdown, which is easy to forget to do!

See https://github.com/tom-james-watson/old-reddit-redirect/pull/113#issuecomment-2044337140 for my answer to this, though.

**Comment by MesaBlack** [comment]
go away, bennyschimdt.

**Comment by pabuisson** [comment]
@tom-james-watson thanks for your reply and sorry for the noise. I'm not surprised by your reply and the rationale, even though I still think having one single solid addon for these similar needs would be the best, I understand your point. Thanks for your time and reply!

**Comment by tom-james-watson** [comment]
I think it's actually not possible anymore anyway - Reddit is redirecting new.reddit.com to www.reddit.com.
