### ISSUE TITLE
"The page isn’t redirecting properly" when trying to login

### ISSUE THREAD

**Issue by brent-holland** [tom-james-watson/old-reddit-redirect#120]
It appears reddit is trying to break old reddit by disabling login and redirecting to new reddit.  When you try to login, you just get a stream of 301's ending with a NS_ERROR_REDIRECT_LOOP.  Maybe we need to add login to the excludes?

**Comment by Radagast** [comment]
I'm not convinced this is an issue with the addon. There are quite a few posts in r/bugs and r/help regarding this. There are also interface changes. The Sidebar login option is missing. I'm guessing Reddit is either broken or they're making changes...

**Comment by Enerccio** [comment]
It is an issue with the plugin. Or rather reddit changed the login to always use new reddit even when old reddit page is used. So now plugin tries to redirect from login page back to old reddit and it break it I guess.

**Comment by tom-james-watson** [comment]
Well given I can't fix this for a few days, let's just see. If it's still broken, I'll release a fix next week.

**Comment by tyfighter** [comment]
The login boxes showed back up on old reddit this morning for me, and I'm able to log in from firefox. Maybe this was an oversight and it's been fixed?

**Comment by tom-james-watson** [comment]
Yeah I just checked and it seems to be back to normal, which is good! Let me know if this happens again and we can deploy a fix in the extension.

**Comment by brent-holland** [comment]
Seems fixed on reddit, thanks all

**Comment by aboynton1uop** [comment]
This still appears to be an issue. When I attempt to browse Reddit from a shared network, I'm presented with the "whoa there, pardner! Your request has been blocked due to a network policy" 403 page, and selecting the "login" link from that page (which attempts to bring me to www.reddit.com/login) still produces "This page isn't redirecting properly". Manually altering that URL to read "old.reddit.com/login" changes nothing; I have to disable the extension, log in, then re-enable it. This occurs on desktop Firefox and Firefox ESR (on Debian) and Firefox mobile (on Android) alike.

**Comment by aboynton1uop** [comment]
> Yeah I just checked and it seems to be back to normal, which is good! Let me know if this happens again and we can deploy a fix in the extension.

This still appears to be an issue. When I attempt to browse Reddit from a shared network, I'm presented with the "whoa there, pardner! Your request has been blocked due to a network policy" 403 page, and selecting the "login" link from that page (which attempts to bring me to [www.reddit.com/login](http://www.reddit.com/login)) still produces "This page isn't redirecting properly". Manually altering that URL to read "old.reddit.com/login" changes nothing; I have to disable the extension, log in, then re-enable it. This occurs on desktop Firefox and Firefox ESR (on Debian) and Firefox mobile (on Android) alike.

**Comment by Ottaviocr** [comment]
Today, when logging in, I am redirected to the new reddit page. I log in fine and then I have to refresh the page to go back to old.reddit.com. It's not the end of the world but it is annoying

**Comment by Ottaviocr** [comment]
It might be related to this:

https://old.reddit.com/r/help/comments/1cssv6w/changes_to_old_reddit_login_flow/

**Comment by tom-james-watson** [comment]
When logging in with the new flow on old.reddit.com, I am sent to old.reddit.com/login, and at no point leave old.reddit.com.

It seems to be working fine to me.

**Comment by darth-crunchus** [comment]
Thanks.  For whatever reason, after clearing cookies and cache (ironically, due to issues with reddit loading and encountering errors), I tried to log back into reddit,com and it said I was blocked, and I couldn't get to the login page.  Finally found this github post, and I tried logging in from old.reddit.com, which got me back into my account.  So, it seems, that as of Oct. 14, 2024, this issue is still alive and kicking
