### ISSUE TITLE
Firefox - Version 2 not working

### ISSUE THREAD

**Issue by Velphae** [tom-james-watson/old-reddit-redirect#136]
As of yesterday (8/28) version 2 is not working on firefox.

**Comment by skippybosco** [comment]
I just tested it working on the latest FireFox:


https://github.com/user-attachments/assets/0027c8d3-a946-4070-96cd-f1c5112837a2

Can you elaborate on your steps to reproduce.

What version of Firefox are you using?

What version of the extension are you using? (have you verified it is enabled?)

What other extensions do you have enabled? Disable everything but old-reddit-redirect and restart browser. Are you still having issues?

What is the exact URL you are testing with? example:
https://www.reddit.com/r/Showerthoughts/comments/1f3j43m/most_superheroes_couldnt_eat_fast_enough_to/

....and what happens when you click the link?

**Comment by Velphae** [comment]
I am talking about version 2 of the reddit format. 
![image](https://github.com/user-attachments/assets/134c2625-428d-4421-b02f-dd7b89f902e8)

**Comment by tom-james-watson** [comment]
This has nothing to do with this extension. All this extension does is ensure that Reddit will always load old.reddit.com. User preferences for switching between any other version of Reddit will always be overridden by this extension. If you don't want that, then you'll want to remove the extension.

**Comment by skippybosco** [comment]
> I am talking about version 2 of the reddit format.

In addition, from your screenshot, it looks like you are using [UI changer for reddit extension](https://chromewebstore.google.com/detail/ui-changer-for-reddit/bfcldjodnnkndfccfjndmdlppfkmccgh). Having two extensions that compete to change the URL (old.reddit.com, new.reddit.com, sh.reddit.com, etc) is going to cause unpredictable results.

If you prefer just using the old interface, [Old Reddit Redirect](https://chromewebstore.google.com/detail/old-reddit-redirect/dneaehbmnbhcippjikoajpoabadpodje) will be the safest and most efficient option for you. Remove the other extension and enable Old Reddit Redirect it should direct you to old.reddit.com without issue.
