### ISSUE TITLE
No longer working on Brave browser

### ISSUE THREAD

**Issue by jersharocks** [tom-james-watson/old-reddit-redirect#139]
The extension worked flawlessly until yesterday afternoon. I've tried uninstalling and reinstalling and it still isn't working. Unsure if there's anything else I could try with a browser extension.

**Comment by tom-james-watson** [comment]
Brave is not a supported browser. Can you please check if it works as expected on chrome? If not, this is a problem with Brave, not the extension.

Regardless:

What other extensions do you have enabled? Disable everything but old-reddit-redirect and restart browser. Are you still having issues?

What is the exact URL you are testing with? example:
https://www.reddit.com/r/Showerthoughts/comments/1f3j43m/most_superheroes_couldnt_eat_fast_enough_to/

....and what happens when you click the link? What URL does it go to (old.reddit.com?) can you share a screenshot.

**Comment by jersharocks** [comment]
I appreciate you looking into it despite Brave not being supported!

I have a ton of extensions but I can list them if you need me to.

The weirdest thing is that it seems to be an intermittent issue. I went down to just old reddit redirect and tested it. I closed the browser and went to reddit.com and it redirected to old.reddit.com. Then I tried again and it worked as expected. But when I checked a third time it did not redirect and just went to reddit.com. Maybe it's an issue with my internet or something. I'll keep playing around with it and see if I can figure anything out.

**Comment by tom-james-watson** [comment]
I think that if it's not recreatable in Chrome then it's an issue with Brave, sorry.

**Comment by skippybosco** [comment]
> I have a ton of extensions but I can list them if you need me to.

I'd try testing with just old-reddit-redirect enabled and follow your same pattern of opening and closing trying to recreate the issue. If you can't, it may be that one of the other extensions is creating a conflict.

I've tested it 10 times in a row with the latest Brave browser and was not able to reproduce a failure. 

https://github.com/user-attachments/assets/490f2f4b-7094-4056-ad27-4efd23328ac5

If you're not able to reproduce it with all the other extensions disabled, it may be necessary to look into each of the other extensions and see if you can find which one is causing the conflict.

**Comment by jersharocks** [comment]
I figured it out. The issue was that a bookmark on Speed Dial 2 New tab was set to reddit.com and it did not redirect even with old-reddit-redirect enabled. Every other way of accessing reddit was redirecting properly. I just changed the bookmark to old.reddit.com and now everything is working great. Thanks for all the help and suggestions.
