### ISSUE TITLE
Posts with multiple images have the URL for gallery properly linked, but clicking on it redirects back to old.reddit.com

### ISSUE THREAD

**Issue by skippybosco** [tom-james-watson/old-reddit-redirect#147]
When viewing a post that has multiple reddit hosted images they are displayed using the gallery URL. The URL is properly formatted, but clicking on it redirects back to old.reddit.com which prevents loading of the gallery.

Example:

https://old.reddit.com/r/GettingShredded/comments/1halvxr/im_the_leanest_ive_ever_been_at_the_age_of_43/

The title correctly links to Gallery at:

https://www.reddit.com/gallery/1halvxr

But clicking it just takes you back to 

https://old.reddit.com/r/GettingShredded/comments/1halvxr/im_the_leanest_ive_ever_been_at_the_age_of_43/

https://github.com/user-attachments/assets/0318ff10-18f2-4dd1-a4f7-5690552ed898

**Comment by skippybosco** [comment]
Submitted fix in pull request 148

**Comment by RandalR** [comment]
Yes please I am having the same issue and was just about to submit a new issue.  It has been doing that for a while now, but I think it once worked correctly?    I just tried on a new system that only had RES on it before and it was giving an error without this plug-in.  I thought to try it with the plug-in but it did not fix the problem.

This add-on is such a needed fix, I _really_ appreciate the efforts on it!  Thank you!!

**Comment by tom-james-watson** [comment]
What are you expecting to happen when you click that link? Open the new reddit page?

I still get the standard in-page gallery that I've always got, so I can just navigate between the images directly on old reddit.

Also, with your branch, I still end up back on the same page. https://www.reddit.com/gallery/1halvxr redirects to https://www.reddit.com/r/GettingShredded/comments/1halvxr/im_the_leanest_ive_ever_been_at_the_age_of_43/ which will then be picked up by the extension.

I suspect the behaviour on reddit itself has changed since you opened the PR? This is how it's always worked for me though, as far as I can remember.

https://github.com/user-attachments/assets/cc276801-f4d2-42d6-a9d7-39c2f82ae803

**Comment by skippybosco** [comment]
Sorry it was not evident in the video above I shared:

1) Click on the link, a new tab opens

2) The tab is just the same old.reddit.com link and no image is displayed

One thing I notice different from your video and mine is that you are logged out. When I am logged out I see the same as you, but logging in provides the behavior described. Logged in, the only way I'm able to correct it is by excluding gallery. 

Reddit is busy making changes :-/

**Comment by tom-james-watson** [comment]
For me it works exactly the same when logged in.

But what I don't understand is what your *expected* behaviour is. What are you saying *should* happen?

**Comment by skippybosco** [comment]
Logged out looks the same as yours:

![image](https://github.com/user-attachments/assets/01bb06ce-f3ee-43d0-99f1-9fb2201fbfa8)

Logged in does not display images and clicking the title to open the gallery redirects back to the same old.reddit.com with no images displayed

![image](https://github.com/user-attachments/assets/114f205d-67c6-4b48-a354-4b8b0a6fc483)

What _should_ happen is when clicking on the title should open the new page with gallery as the images are not visible otherwise. I've tested with multiple accounts. And nothing evident in account settings that would contribute, but worth comparing to your test account to see if this is a setting or an A/B Reddit testing.

![image](https://github.com/user-attachments/assets/845f4b60-89bb-44fb-bc9f-452418e026b5)

With the extension disabled, it behaves the way that I expect, despite being on old.reddit.com, clicking a gallery link takes you to the www.reddit.com to display the gallery.

**Comment by tom-james-watson** [comment]
I think that's a problem with reddit itself - it should always display the images inline in old reddit. There was a brief time in the past where we had to go to the new reddit gallery to see the images, but it was horrible UX. I think the real problem here is that you're not getting the images inline when logged in for some reason, but I don't think that's to do with the extension.

Here's my settings for if you want to test what the difference might be

<img width="859" alt="image" src="https://github.com/user-attachments/assets/1406c116-941f-4d79-8d25-6488d3a19a21" />

**Comment by skippybosco** [comment]
Thanks @tom-james-watson . So it is a bit of a hack, but if I disable compressed links, and then enable "show thumbnail next to links", then click the blue arrow next to the thumbnail I'm able to get a legacy mechanism to cycle through images on post without having to load the gallery. I'll miss compressed links, but this is likely a better solution.

**Comment by tom-james-watson** [comment]
Glad you got it working 🫶
