### ISSUE TITLE
Backslash underscore on user-posted links

### ISSUE THREAD

**Issue by peberlein** [tom-james-watson/old-reddit-redirect#56]
Examples in posts:
https://old.reddit.com/r/Genshin_Impact/comments/p6fu39/has_anyone_figured_what_the_interaction_between/h9d51p8/ 
https://old.reddit.com/r/Genshin_Impact/comments/p6nj8c/yet_another_hidden_commission_achievement_this/h9eav7a/

Their links contain`\_` which appears to be accepted on new.reddit.com, but goes to 'page not found' on old.reddit.com.  Perhaps the redirect could translate `\_` to `_` on old.reddit.com?

(Thanks for the addon btw.  I find it really useful.)

**Comment by tom-james-watson** [comment]
Those links are invalid links, so really this is a bug in old.reddit.com, not the extension. Go to https://www.reddit.com/r/Genshin%5C_Impact/comments/k43wzc/zhonglis%5C_holde%5C_targets%5C_petrified%5C_enemies%5C_new/ with the extension disabled and it will not load. If you load www.reddit.com/r/Genshin_Impact/comments/p6fu39/has_anyone_figured_what_the_interaction_between/h9d51p8/ with the extension turned off, the link does not contain those `\`s.

Really this should be fixed by reddit.

**Comment by peberlein** [comment]
Thanks for your analysis.  Yesterday the invalid links loaded properly; today they do not.  Definitely something weird going on with reddit servers or CDNs.  Feel free to close this issue.

**Comment by tom-james-watson** [comment]
OK! Thanks for the report 👍
