### ISSUE TITLE
Getting popups to sign in on allizom.org, 

### ISSUE THREAD

**Issue by riaanjutte** [tom-james-watson/old-reddit-redirect#69]
A week or so ago Firefox started opening a request to sign in window to allizom.org every time I refreshed the reddit tab. I have tried signing in using my Google account to no avail. By process of elimination of disabling each extension one by one it became obvious that the Old Reddit Redirect plugin was the cause of the issue.

**Comment by tom-james-watson** [comment]
I'm sorry but this simply cannot be true. The entirety of the code of the extension is available in this repository and the addon on addons.mozilla.org is the exact same code. The extension is also security reviewed by Firefox, which you can see by the absence of the warning on the listing warning about it not being verified.

I suggest that you keep looking at other alternative sources of your issue, because it's not this extension. I would suggest disabling the extension and confirming that it still happens.

**Comment by riaanjutte** [comment]
Thanks for the quick response. You are correct, it was actually the Reddit Enhancement Suite that caused the popup. After disabling and re-enabling it the issue went away. Apologies for the mistaken conclusion I arrived at.

**Comment by tom-james-watson** [comment]
No problems. That's a bit worrying RE Reddit Enhancement Suite :confused:

**Comment by riaanjutte** [comment]
Just a quick update regarding this issue: It happens when you're signed into multiple Google accounts at the same time. It can be resolved by specifying the Google account (email) you want to use in the RES settings.
