### ISSUE TITLE
Some Gallery Pages Broken

### ISSUE THREAD

**Issue by WithThisHerring** [tom-james-watson/old-reddit-redirect#95]
Using version 1.7.3

Most gallery pages work great, but some are just a single link image.

Example broken page:
https://old.reddit.com/r/DIY/comments/168rz65/birds_of_vermont_builtin_bookcase/

The image link is to https://www.reddit.com/gallery/168rz65 , which in turn is redirected to the starting point https://old.reddit.com/r/DIY/comments/168rz65/birds_of_vermont_builtin_bookcase/

I did try this old.reddit URL in a clean profile where it shows just that same single image, so it's not uBlock Origin.

Maybe gallery links shouldn't be redirected?  Or maybe it needs to be a bug report to Reddit?  I don't know enough about Reddit or addons to guess.

Does not look like it is related to #55 , as one cannot see the other images on the comments page.
Maybe related to old issue #72 ?

Thank you so much for this wonderful addon!  It makes Reddit actually usable!

**Comment by tom-james-watson** [comment]
I think what is happening here is that old reddit has a limit on how many images it will show from a gallery before it just doesn't let you see the images inside old reddit itself.

For example look at another post that has a gallery with less images: https://old.reddit.com/r/DIY/comments/16fdckc/any_idea_what_is_causing_these_holes_next_to_my/

The link text still points to the new reddit gallery, which redirects back to the old reddit post, but the images can be browsed inside old reddit and so this doesn't matter.

These gallery links are found all over the frontpage of reddit and without the exisiting redirect, you end up accidentally navigating through to these new reddit gallery links (eg https://new.reddit.com/gallery/168rz65) all the time by mistake. These pages are annoying because a) they're not old reddit and b) you can't even see the comments.

I think stopping redirecting the gallery links would be more annoying than handling this, as far as I can tell, small edge case of huge galleries.

I'd like to get an idea of whether I'm underestimating how often this is happening though. If this is something you are seeing often and are annoyed by, and would prefer to be linked through to things like https://new.reddit.com/gallery/168rz65 from the main page as a "fix", then give the OP a 👍

**Comment by loujar** [comment]
I'm on 1.6.1 and experiencing similar behavior. Whenever I click on a gallery preview, the extension seems to redirect me to [this random comment](https://old.reddit.com/r/funny/comments/media/nice_hat/) with the actual URL of the link supplied as a query parameter (example: https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fi.redd.it%2Fxph4zncjmgpb1.jpg)

**Comment by tom-james-watson** [comment]
@loujar that is https://github.com/tom-james-watson/old-reddit-redirect/issues/86 and is already fixed. You need to update to the latest version of the extension.

**Comment by loujar** [comment]
thanks! just needed to turn on auto-update for the extension.

Thank you for maintaining this add-on 🙏

**Comment by WithThisHerring** [comment]
I would actually say that maybe just leave current behavior as-is, then.  I have only run into this maybe twice in the last couple months of looking at Reddit.  I had forgotten I could just add "new." to the URL myself.  So I am not giving a "👍" to my original issue comment.

I will not close this issue because I am unsure if you want to let other users continue to weigh in.  :)

**Comment by tom-james-watson** [comment]
Yeah at the moment I don't think it's worth trying to fix this, because the fix is worse than the current situation. The workaround will just have to be to use new.reddit.com, as you suggest.

I think closing this out makes sense 👍

**Comment by Novark** [comment]
@tom-james-watson I know this issue has been closed, however, I just wanted to add my 2 cents:

The way I navigate Reddit in general is to open most posts in a new tab by middle-mouse-clicking the "Comments" button.  When the page loads in a new tab, I can determine if the images were correctly embedded at the top of the post (which, thankfully is often the case).

In some circumstances (outlined above), the images don't embed for whatever reason.  What I would like the option to do is to middle-mouse-click the actual post-link (the `www.reddit.com/gallery/[###]` link) and have that open in a new tab using `new.reddit.com`.

So, the comments would be loaded using `old.reddit.com`, but the `gallery` links would redirect to `new.reddit.com` so that they could still be viewed in a new tab.

Any chance of having this support added to the addon in the form of a checkbox or something?  Something like:

- [x] Allow `old.reddit.com/gallery/` paths to automatically redirect to new-reddit galleries
